add mml_to_phrase func
YoshikawaMasashi/pytoid pull request #1
Opened 2020-05-18 13:37 UTC by yos1up

```python
from toid.high_layer_trial import mml_to_phrase
ph =  mml_to_phrase("o4l8ccggaagrffeeddcr")
```

2020-05-18 13:43 UTC, YoshikawaMasashi requested changes

2020-05-18 13:43 UTC, YoshikawaMasashi commented on toid/mml/core.py
> +・「コンピュータサイエンスのあらゆる分野に精通しているライブコーダー」
流石にここら辺消して欲しいです・・

2020-05-18 13:55 UTC, yos1up commented on toid/mml/core.py
> +・「コンピュータサイエンスのあらゆる分野に精通しているライブコーダー」
削除しました

2020-05-19 01:17 UTC, YoshikawaMasashi approved these changes

2020-05-19 01:17 UTC, merged